name: Build LaTeX document
on:
  push:
    branches: [ main ]
    paths:
      - '**.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        run: make

      # - name: Compile LaTeX document
      #   uses: xu-cheng/latex-action@v2

      # Upload the PDF file as an artifact
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      # # or instead commit and push the PDF file (doesn't work yet)
      # - name: mark dir as safe
      #   run: |
      #     git config --global --add safe.directory $PWD

      # - name: Commit and push PDF file
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: main.pdf
  